<a href="https://colab.research.google.com/github/Henry6833/Henry6833.github.io/blob/main/Milestone1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Students' perception of Artificial Intelligence effects on Cognitive Engagement

---

Randall Herrera and Henry Mulvihill

#**The Project's Goal:**

The team, **Randall Herrera** and **Henry Mulvihill** will be investigating multiple different student's insights on how the use of AI affects their cognitive engagement. We want to showcase the student's learning behaviors with ai and their feeback on cognitive engagement using it. We emphasized searching for survey datasets that asked students the following: frequency usage with AI tools, perceived reliance on it, their perceived effects on critical thinking, and background about the student. We have found two survey datasets that give great measurement and feedback for this project.

# **The Datasets:**

- Our main dataset, [AI Dependency and Academic Vulnerability](https://www.kaggle.com/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability), contains responses from 1104 college students from Bangladesh responses based on several questions pertaining to how they use Artificial Intelligence tools in academics. The main topics these questions answer are how dependent students are on these tools for learning and whether their usage with cognitive offload is harmful.


- The second dataset we chose, [GenAI Impact on Critical Thinking:BD Study](https://www.kaggle.com/datasets/mehedirafidsm/genai-impact-on-critical-thinking-bd-study), contains 400 responses from college students from Bangladesh. These questions asked the students to self evaluate their reliance on AI, how frequently they use it, and a 1-5 agreement scale.

#**Our Collaboration Plan:**

We have decided to meet up for 15 minutes after every Data Science lecture to speak, catch up on ideas to refine, expand, and assist one another's ideas for our approach. We also established a flexible space to meet via Discord every Tuesday or Saturday to inform changes and work simultanously in the project. Outside of meetings we would commit changes we've made to our GitHub repository independently. After anyone made changes, they would text or call the other one to discuss the new additions to the project.

In [3]:
import pandas as pd
import numpy as np
import kagglehub
import os

This first cell contains all of the imports that will be required for the code in this project. We will require Pandas for data structures like DataFrames and Series to display the data, and NumPy to perform numerical analysis.


Additionally, Python's built-in os module enables interaction with the operating system: files, folders, and paths within colab's virtual machine.

In [4]:
# Download latest version
path = kagglehub.dataset_download("mdjhirulislam/ai-dependency-and-academic-vulnerability")
print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/1.archive...

100%|██████████| 11.7k/11.7k [00:00<00:00, 9.07MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/versions/1

Using the `kagglehub` module imported earlier, we can get the path of one of our datasets directly from Kaggle's API. What kagglehub does is create a new folder to place our dataset, and the `path` variable contains the location of that folder. This is one way for retrieving the data, even if someone who does not have the datasets stored in their computer wishes to access the data.

In [5]:
os.listdir(path)

['AI Dependency and Academic Vulnerability in Higher Education A Survey Dataset from Bangladesh.csv']

We might want to learn what the folder that `kagglehub` created contains. `os.listdir(path)` allows us to see everything inside that folder, returned into a Python list. Alternatively, we can run the `!ls` command in the terminal:

In [6]:
%cd /root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/versions/1
!ls

/root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/versions/1
'AI Dependency and Academic Vulnerability in Higher Education A Survey Dataset from Bangladesh.csv'

In this case, we can use the `path` variable to 'build up' the appropiate url based on our system's file directory by passing it as argument to the `os.path.join(...)` function call, where we look up the folder where `kagglehub` originally downloaded the dataset and its name to join them and obtain the full url. The `DataFrame` is ready to be analyzed.

In [7]:
dependency_survey = pd.read_csv(os.path.join(path, "AI Dependency and Academic Vulnerability in Higher Education A Survey Dataset from Bangladesh.csv"))
dependency_survey.head()

,Gender,Age,Name of University,Academic Level,Current CGPA,Daily AI Usage Time,I verify AI-generated information before using it in academic work.,I can study and complete tasks effectively without any AI support.,My first instinct for any academic doubt is to ask an AI rather than checking books or notes.,I find it harder to recall information that I have previously generated using AI.,"When using AI, I prioritize completing assignments quickly rather than fully understanding the subject matter.",I often use AI-generated responses without making any major modifications.,I feel less confident in my writing and analytical skills when I am not using AI.,My critical thinking ability has weakened due to reliance on AI tools.,I often submit academic work without fully understanding the content generated by AI.
0,Male,24-26,Jahangirnagar University,Master's,3.01-3.50,1-3 hours,Disagree,Disagree,Strongly Agree,Agree,Neutral,Agree,Strongly Agree,Strongly Agree,Agree
1,Male,20-23,Daffodil International University,Undergraduate,2.51-3.00,1-3 hours,Strongly Agree,Agree,Neutral,Agree,Disagree,Strongly Agree,Agree,Agree,Strongly Agree
2,Female,20-23,Daffodil International University,Undergraduate,3.01-3.50,1-3 hours,Agree,Neutral,Agree,Disagree,Agree,Disagree,Agree,Agree,Disagree
3,Female,20-23,Daffodil International University,Undergraduate,3.01-3.50,1-3 hours,Agree,Neutral,Neutral,Disagree,Agree,Disagree,Neutral,Strongly Agree,Agree
4,Female,20-23,Primeasia University,Undergraduate,Above 3.50,Less than 1 hour,Agree,Neutral,Neutral,Disagree,Agree,Neutral,Neutral,Disagree,Disagree

Another method to get a dataset is the following:

In [8]:
# Raw urls of the datasets obtained from the data/ folder in the GitHub source repository
url_dataset_1 = "https://raw.githubusercontent.com/Henry6833/Henry6833.github.io/refs/heads/main/data/Survey_Data_GenAI_Critical_Thinking_Bangladesh.csv"

We retrieve the raw url directly from the project's GitHub repository, and store it in a variable.

In [9]:
ct_survey = pd.read_csv(url_dataset_1)
ct_survey.head()

,Year,Gender,Department,Usage_Freq,Primary_Tool,RelyOnAI_Answers,ReducesCritical,LimitsSkills,MemoryRetentionDrop,CT1_IndependentAnalysis,...,PROD2_TaskCompletion,PROD3_ConceptClarity,CGPA,CT_Composite,Dependency_Composite,Benefit_Composite,Cluster,CT_Sum,Dependency_Sum,Benefit_Sum
0,4,Male,BBA,Often,Gemini,3,3,2,2,2,...,5,4,3.50,1.75,2.50,4.6,Balanced / Moderate Users,7,10,23
1,2,Female,CSE,Often,ChatGPT,4,4,4,5,4,...,3,2,2.90,4.00,4.25,2.4,Highly Dependent / At-Risk Users,16,17,12
2,4,Female,Civil,Daily,Microsoft Copilot,4,4,5,5,4,...,1,2,3.58,3.25,4.50,1.6,Highly Dependent / At-Risk Users,13,18,8
3,3,Male,BBA,Daily,ChatGPT,5,5,5,5,3,...,4,4,3.35,2.50,5.00,3.8,"Strategic Users (High Reliance, High Benefit)",10,20,19
4,1,Prefer not to say,CSE,Daily,ChatGPT,4,3,3,2,4,...,4,5,3.29,4.00,3.00,4.4,"Strategic Users (High Reliance, High Benefit)",16,12,22

This variable has been simply passed to Pandas' `.read_csv(...)` method to store the dataset as a `DataFrame`.

# **Data Tidying:**
The first principle of Data Tidying says that each variable forms a column and has values. While the `dependency_survey` dataset satisfies this principle, the variables names are full sentences for the questions, rather than concise names that capture a concrete feature for an observation. In `dependency_survey`, an observation represents a student that filled the form. We modify the column names to be more readable:

In [13]:
original_columns = dependency_survey.columns.tolist()

new_cols = ["gender", "age_group", "university", "academic_level", "current_cgpa",
            "daily_ai_use", "verifies_ai_output", "can_study_without_ai",
            "ai_first_instinct", "harder_recall_ai_content", "speed_over_understanding",
            "uses_ai_unedited", "less_confident_without_ai", "ct_weakened",
            "submits_without_understanding"]

codebook = dict(zip(new_cols, original_columns))
codebook["speed_over_understanding"]

'When using AI, I prioritize completing assignments quickly rather than fully understanding the subject matter.'

The codebook variable simply allows us to map the new column's name with the corresponding question from the survey.

In [14]:
dependency_survey.columns = new_cols
dependency_survey.head()

,gender,age_group,university,academic_level,current_cgpa,daily_ai_use,verifies_ai_output,can_study_without_ai,ai_first_instinct,harder_recall_ai_content,speed_over_understanding,uses_ai_unedited,less_confident_without_ai,ct_weakened,submits_without_understanding
0,Male,24-26,Jahangirnagar University,Master's,3.01-3.50,1-3 hours,Disagree,Disagree,Strongly Agree,Agree,Neutral,Agree,Strongly Agree,Strongly Agree,Agree
1,Male,20-23,Daffodil International University,Undergraduate,2.51-3.00,1-3 hours,Strongly Agree,Agree,Neutral,Agree,Disagree,Strongly Agree,Agree,Agree,Strongly Agree
2,Female,20-23,Daffodil International University,Undergraduate,3.01-3.50,1-3 hours,Agree,Neutral,Agree,Disagree,Agree,Disagree,Agree,Agree,Disagree
3,Female,20-23,Daffodil International University,Undergraduate,3.01-3.50,1-3 hours,Agree,Neutral,Neutral,Disagree,Agree,Disagree,Neutral,Strongly Agree,Agree
4,Female,20-23,Primeasia University,Undergraduate,Above 3.50,Less than 1 hour,Agree,Neutral,Neutral,Disagree,Agree,Neutral,Neutral,Disagree,Disagree

Now, we simply renamed our columns. This way, the data table looks less cluttered, and the new variables from our columns successfully describe the a specific feature of the observation.

In [16]:
dependency_survey.dtypes

gender                           object
age_group                        object
university                       object
academic_level                   object
current_cgpa                     object
daily_ai_use                     object
verifies_ai_output               object
can_study_without_ai             object
ai_first_instinct                object
harder_recall_ai_content         object
speed_over_understanding         object
uses_ai_unedited                 object
less_confident_without_ai        object
ct_weakened                      object
submits_without_understanding    object
dtype: object

The `dtype` for this dataset is `object` for all variables, which immediately implies the data is categorical. This is true in many cases, but pandas fails to interpret the statistical data type in many other. We provide a deeper insight:

In [18]:
dependency_survey.loc[:, "verifies_ai_output":].head()

,verifies_ai_output,can_study_without_ai,ai_first_instinct,harder_recall_ai_content,speed_over_understanding,uses_ai_unedited,less_confident_without_ai,ct_weakened,submits_without_understanding
0,Disagree,Disagree,Strongly Agree,Agree,Neutral,Agree,Strongly Agree,Strongly Agree,Agree
1,Strongly Agree,Agree,Neutral,Agree,Disagree,Strongly Agree,Agree,Agree,Strongly Agree
2,Agree,Neutral,Agree,Disagree,Agree,Disagree,Agree,Agree,Disagree
3,Agree,Neutral,Neutral,Disagree,Agree,Disagree,Neutral,Strongly Agree,Agree
4,Agree,Neutral,Neutral,Disagree,Agree,Neutral,Neutral,Disagree,Disagree

In [15]:
dependency_survey.value_counts()

gender  age_group  university                         academic_level  current_cgpa  daily_ai_use       verifies_ai_output  can_study_without_ai  ai_first_instinct  harder_recall_ai_content  speed_over_understanding  uses_ai_unedited  less_confident_without_ai  ct_weakened  submits_without_understanding
Female  20-23      Daffodil International University  Undergraduate   3.01-3.50     Less than 1 hour   Agree               Agree                 Disagree           Disagree                  Disagree                  Disagree          Disagree                   Disagree     Strongly Disagree                63
                                                                                    More than 3 hours  Disagree            Disagree              Agree              Agree                     Agree                     Agree             Agree                      Agree        Strongly Agree                   31
                                                                                    Less than 1 hour   Agree               Agree                 Disagree           Disagree                  Disagree                  Disagree          Disagree                   Disagree     Disagree                         12
Male    20-23      Daffodil International University  Undergraduate   3.01-3.50     Less than 1 hour   Agree               Agree                 Disagree           Disagree                  Disagree                  Disagree          Disagree                   Disagree     Strongly Disagree                11
Female  20-23      Daffodil International University  Undergraduate   2.51-3.00     Less than 1 hour   Agree               Agree                 Disagree           Disagree                  Disagree                  Disagree          Disagree                   Disagree     Strongly Disagree                 6
                                                                                                                                                                                                                                                                                                                   ..
        24-26      Primeasia University               Master's        3.01-3.50     More than 3 hours  Agree               Neutral               Agree              Agree                     Disagree                  Neutral           Agree                      Neutral      Disagree                          1
                                                                                                       Neutral             Agree                 Agree              Agree                     Neutral                   Neutral           Agree                      Agree        Agree                             1
                                                                      Above 3.50    More than 3 hours  Neutral             Agree                 Agree              Disagree                  Agree                     Disagree          Agree                      Neutral      Disagree                          1
                                                      Undergraduate   3.01-3.50     1-3 hours          Agree               Disagree              Neutral            Agree                     Disagree                  Agree             Neutral                    Neutral      Agree                             1
                   Jahangirnagar University           Undergraduate   Above 3.50    Less than 1 hour   Strongly Agree      Agree                 Disagree           Disagree                  Disagree                  Disagree          Disagree                   Disagree     Disagree                          1
Name: count, Length: 942, dtype: int64